
<!DOCTYPE HTML>

<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Network Debug and Troubleshooting - Ansible - W3cubDocs</title>
  
  <meta name="description" content="Starting with Ansible version 2.1, you can now use the familiar Ansible models of playbook authoring and module development to manage heterogeneous &hellip;">
  <meta name="keywords" content="network, debug, and, troubleshooting, guide, -, ansible">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/ansible/network_debug_troubleshooting/">
  <link href="/favicon.png" rel="icon">
  <link type="text/css" rel="stylesheet" href="/assets/application-e0f881b0fce8cbe96f33dadc355b7159d5d2912911231446d60eb8f9caffa802.css">
  <script type="text/javascript" src="/assets/application-8fc46316434047265cd383f02b8e7f434ed7dec4a59f920dd633deef8d488d1b.js"></script>
  <script src="/json/ansible.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/ansible/" class="_nav-link" title="" style="margin-left:0;">Ansible</a></span>
  
  <nav class="_nav">
    <a href="/app/" class="_nav-link ">App</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<div class="_page _sphinx">
				
<h1 id="network-debug-troubleshooting">Network Debug and Troubleshooting Guide</h1>   <ul id="network-debug-and-troubleshooting-guide"> <li><a class="reference internal" href="#introduction" id="id2">Introduction</a></li> <li>
<a class="reference internal" href="#how-to-troubleshoot" id="id3">How to troubleshoot</a><ul> <li><a class="reference internal" href="#enabling-networking-logging-and-how-to-read-the-logfile" id="id4">Enabling Networking logging and how to read the logfile</a></li> <li><a class="reference internal" href="#isolating-an-error" id="id5">Isolating an error</a></li> </ul> </li> <li>
<a class="reference internal" href="#category-unable-to-open-shell" id="id6">Category “Unable to open shell”</a><ul> <li><a class="reference internal" href="#error-errno-2-name-or-service-not-known" id="id7">Error: “[Errno -2] Name or service not known”</a></li> <li><a class="reference internal" href="#error-authentication-failed" id="id8">Error: “Authentication failed”</a></li> <li><a class="reference internal" href="#error-connecting-to-host-hostname-returned-an-error-or-bad-address" id="id9">Error: “connecting to host &lt;hostname&gt; returned an error” or “Bad address”</a></li> <li><a class="reference internal" href="#error-no-authentication-methods-available" id="id10">Error: “No authentication methods available”</a></li> <li><a class="reference internal" href="#clearing-out-persistent-connections" id="id11">Clearing Out Persistent Connections</a></li> </ul> </li> <li>
<a class="reference internal" href="#timeout-issues" id="id12">Timeout issues</a><ul> <li><a class="reference internal" href="#timeouts" id="id13">Timeouts</a></li> </ul> </li> <li>
<a class="reference internal" href="#playbook-issues" id="id14">Playbook issues</a><ul> <li><a class="reference internal" href="#error-invalid-connection-specified-expected-connection-local-got-ssh" id="id15">Error: “invalid connection specified, expected connection=local, got ssh”</a></li> <li><a class="reference internal" href="#error-unable-to-enter-configuration-mode" id="id16">Error: “Unable to enter configuration mode”</a></li> </ul> </li> </ul>
   <h2 id="introduction">Introduction</h2> <p>Starting with Ansible version 2.1, you can now use the familiar Ansible models of playbook authoring and module development to manage heterogeneous networking devices. Ansible supports a growing number of network devices using both CLI over SSH and API (when available) transports.</p> <p>This section discusses how to debug and troubleshoot network modules in Ansible 2.3.</p>   <h2 id="how-to-troubleshoot">How to troubleshoot</h2> <p>This section covers troubleshooting issues with Network Modules.</p> <p>Errors generally fall into one of the following categories:</p> <table class="docutils field-list" frame="void" rules="none"> <col class="field-name"> <col class="field-body">  <tr><th class="field-name" colspan="2">Authentication issues:</th></tr> <tr>
<td> </td>
<td class="field-body">
<ul class="first simple"> <li>Not correctly specifying credentials</li> <li>Remote device (network switch/router) not falling back to other other authentication methods</li> <li>SSH key issues</li> </ul> </td> </tr> <tr>
<th class="field-name">Timeout issues:</th>
<td class="field-body">
<ul class="first simple"> <li>Can occur when trying to pull a large amount of data</li> <li>May actually be masking a authentication issue</li> </ul> </td> </tr> <tr><th class="field-name" colspan="2">Playbook issues:</th></tr> <tr>
<td> </td>
<td class="field-body">
<ul class="first last simple"> <li>Use of <code>delegate_to</code>, instead of <code>ProxyCommand</code>
</li> <li>Not using <code>connection: local</code>
</li> </ul> </td> </tr>  </table> <div class="admonition warning"> <p class="first admonition-title">Warning</p> <p><code>unable to open shell</code></p> <p class="last">The <code>unable to open shell</code> message is new in Ansible 2.3, it means that the <code>ansible-connection</code> daemon has not been able to successfully talk to the remote network device. This generally means that there is an authentication issue. See the “Authentication and connection issues” section in this document for more information.</p> </div>  <h3 id="enable-network-logging">Enabling Networking logging and how to read the logfile</h3> <p id="enabling-networking-logging-and-how-to-read-the-logfile"><strong>Platforms:</strong> Any</p> <p>Ansible 2.3 features improved logging to help diagnose and troubleshoot issues regarding Ansible Networking modules.</p> <p>Because logging is very verbose it is disabled by default. It can be enabled via the <a class="reference internal" href="../config/#envvar-ANSIBLE_LOG_PATH" id="index-0"><code>ANSIBLE_LOG_PATH</code></a> and <a class="reference internal" href="../config/#envvar-ANSIBLE_DEBUG" id="index-1"><code>ANSIBLE_DEBUG</code></a> options:</p> <pre data-language="YAML"># Specify the location for the log file
export ANSIBLE_LOG_PATH=~/ansible.log
# Enable Debug
export ANSIBLE_DEBUG=True

# Run with 4*v for connection level verbosity
ansible-playbook -vvvv ...
</pre> <p>After Ansible has finished running you can inspect the log file:</p> <pre data-language="YAML">2017-03-30 13:19:52,740 p=28990 u=fred |  creating new control socket for host veos01:22 as user admin
2017-03-30 13:19:52,741 p=28990 u=fred |  control socket path is /home/fred/.ansible/pc/ca5960d27a
2017-03-30 13:19:52,741 p=28990 u=fred |  current working directory is /home/fred/ansible/test/integration
2017-03-30 13:19:52,741 p=28990 u=fred |  using connection plugin network_cli
...
2017-03-30 13:20:14,771 paramiko.transport userauth is OK
2017-03-30 13:20:15,283 paramiko.transport Authentication (keyboard-interactive) successful!
2017-03-30 13:20:15,302 p=28990 u=fred |  ssh connection done, setting terminal
2017-03-30 13:20:15,321 p=28990 u=fred |  ssh connection has completed successfully
2017-03-30 13:20:15,322 p=28990 u=fred |  connection established to veos01 in 0:00:22.580626
</pre> <p>From the log notice:</p> <ul class="simple"> <li>
<code>p=28990</code> Is the PID (Process ID) of the <code>ansible-connection</code> process</li> <li>
<code>u=fred</code> Is the user <code>running</code> ansible, not the remote-user you are attempting to connect as</li> <li>
<code>creating new control socket for host veos01:22 as user admin</code> host:port as user</li> <li>
<code>control socket path is</code> location on disk where the persistent connection socket is created</li> <li>
<code>using connection plugin network_cli</code> Informs you that persistent connection is being used</li> <li>
<code>connection established to veos01 in 0:00:22.580626</code> Time taken to obtain a shell on the remote device</li> </ul> <p>Because the log files are verbose, you can use grep to look for specific information. For example, once you have identified the <code>`pid</code> from the <code>creating new control socket for host</code> line you can search for other connection log entries:</p> <pre data-language="YAML">grep "p=28990" $ANSIBLE_LOG_PATH
</pre>   <h3 id="isolating-an-error">Isolating an error</h3> <p><strong>Platforms:</strong> Any</p> <p>As with any effort to troubleshoot it’s important to simplify the test case as much as possible.</p> <p>For Ansible this can be done by ensuring you are only running against one remote device:</p> <ul class="simple"> <li>Using <code>ansible-playbook --limit switch1.example.net...</code>
</li> <li>Using an ad-hoc <code>ansible</code> command</li> </ul> <p><code>ad-hoc</code> refers to running Ansible to perform some quick command using <code>/usr/bin/ansible</code>, rather than the orchestration language, which is <code>/usr/bin/ansible-playbook</code>. In this case we can ensure connectivity by attempting to execute a single command on the remote device:</p> <pre data-language="YAML">ansible -m eos_command -a 'commands=?' -i inventory switch1.example.net -e 'ansible_connection=local' -u admin -k
</pre> <p>In the above example, we:</p> <ul class="simple"> <li>connect to <code>switch1.example.net</code> specified in the inventory file <code>inventory</code>
</li> <li>use the module <code>eos_command</code>
</li> <li>run the command <code>?</code>
</li> <li>connect using the username <code>admin</code>
</li> <li>inform ansible to prompt for the ssh password by specifying <code>-k</code>
</li> </ul> <p>If you have SSH keys configured correctly, you don’t need to specify the <code>-k</code> parameter</p> <p>If the connection still fails you can combine it with the enable_network_logging parameter. For example:</p> <pre data-language="YAML"># Specify the location for the log file
export ANSIBLE_LOG_PATH=~/ansible.log
# Enable Debug
export ANSIBLE_DEBUG=True
# Run with 4*v for connection level verbosity
ansible -m eos_command -a 'commands=?' -i inventory switch1.example.net -e 'ansible_connection=local' -u admin -k
</pre> <p>Then review the log file and find the relevant error message in the rest of this document.</p>    <h2 id="unable-to-open-shell">Category “Unable to open shell”</h2> <p id="category-unable-to-open-shell"><strong>Platforms:</strong> Any</p> <p>The <code>unable to open shell</code> message is new in Ansible 2.3. This message means that the <code>ansible-connection</code> daemon has not been able to successfully talk to the remote network device. This generally means that there is an authentication issue. It is a “catch all” message, meaning you need to enable <a class="reference internal" href="../intro_configuration/#log-path"><span class="std std-ref">log_path</span></a> to find the underlying issues.</p> <p>For example:</p> <pre data-language="none">TASK [prepare_eos_tests : enable cli on remote device] **************************************************
fatal: [veos01]: FAILED! =&gt; {"changed": false, "failed": true, "msg": "unable to open shell"}
</pre> <p>or:</p> <pre data-language="none">TASK [ios_system : configure name_servers] *************************************************************
task path:
fatal: [ios-csr1000v]: FAILED! =&gt; {
    "changed": false,
    "failed": true,
    "msg": "unable to open shell",
}
</pre> <p>Suggestions to resolve:</p> <p>Follow the steps detailed in <a class="reference internal" href="#enable-network-logging">enable_network_logging</a>.</p> <p>Once you’ve identified the error message from the log file, the specific solution can be found in the rest of this document.</p>  <h3 id="error-errno-2-name-or-service-not-known">Error: “[Errno -2] Name or service not known”</h3> <p><strong>Platforms:</strong> Any</p> <p>Indicates that the remote host you are trying to connect to can not be reached</p> <p>For example:</p> <pre data-language="yaml">2017-04-04 11:39:48,147 p=15299 u=fred |  control socket path is /home/fred/.ansible/pc/ca5960d27a
2017-04-04 11:39:48,147 p=15299 u=fred |  current working directory is /home/fred/git/ansible-inc/stable-2.3/test/integration
2017-04-04 11:39:48,147 p=15299 u=fred |  using connection plugin network_cli
2017-04-04 11:39:48,340 p=15299 u=fred |  connecting to host veos01 returned an error
2017-04-04 11:39:48,340 p=15299 u=fred |  [Errno -2] Name or service not known
</pre> <p>Suggestions to resolve:</p> <ul class="simple"> <li>If you are using the <code>provider:</code> options ensure that it’s suboption <code>host:</code> is set correctly.</li> <li>If you are not using <code>provider:</code> nor top-level arguments ensure your inventory file is correct.</li> </ul>   <h3 id="error-authentication-failed">Error: “Authentication failed”</h3> <p><strong>Platforms:</strong> Any</p> <p>Occurs if the credentials (username, passwords, or ssh keys) passed to <code>ansible-connection</code> (via <code>ansible</code> or <code>ansible-playbook</code>) can not be used to connect to the remote device.</p> <p>For example:</p> <pre data-language="yaml">&lt;ios01&gt; ESTABLISH CONNECTION FOR USER: cisco on PORT 22 TO ios01
&lt;ios01&gt; Authentication failed.
</pre> <p>Suggestions to resolve:</p> <p>If you are specifying credentials via <code>password:</code> (either directly or via <code>provider:</code>) or the environment variable <code id="index-2">ANSIBLE_NET_PASSWORD</code> it is possible that <code>paramiko</code> (the Python SSH library that Ansible uses) is using ssh keys, and therefore the credentials you are specifying are being ignored. To find out if this is the case, disable “look for keys”. This can be done like this:</p> <pre data-language="yaml">export ANSIBLE_PARAMIKO_LOOK_FOR_KEYS=False
</pre> <p>To make this a permanent change, add the following to your <code>ansible.cfg</code> file:</p> <pre data-language="ini">[paramiko_connection]
look_for_keys = False
</pre>   <h3 id="error-connecting-to-host-hostname-returned-an-error-or-bad-address">Error: “connecting to host &lt;hostname&gt; returned an error” or “Bad address”</h3> <p>This may occur if the SSH fingerprint hasn’t been added to Paramiko’s (the Python SSH library) know hosts file.</p> <p>When using persistent connections with Paramiko, the connection runs in a background process. If the host doesn’t already have a valid SSH key, by default Ansible will prompt to add the host key. This will cause connections running in background processes to fail.</p> <p>For example:</p> <pre data-language="yaml">2017-04-04 12:06:03,486 p=17981 u=fred |  using connection plugin network_cli
2017-04-04 12:06:04,680 p=17981 u=fred |  connecting to host veos01 returned an error
2017-04-04 12:06:04,682 p=17981 u=fred |  (14, 'Bad address')
2017-04-04 12:06:33,519 p=17981 u=fred |  number of connection attempts exceeded, unable to connect to control socket
2017-04-04 12:06:33,520 p=17981 u=fred |  persistent_connect_interval=1, persistent_connect_retries=30
</pre> <p>Suggestions to resolve:</p> <p>Use <code>ssh-keyscan</code> to pre-populate the known_hosts. You need to ensure the keys are correct.</p> <pre data-language="shell">ssh-keyscan veos01
</pre> <p>or</p> <p>You can tell Ansible to automatically accept the keys</p> <p>Environment variable method:</p> <pre data-language="YAML">export ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD=True
ansible-playbook ...
</pre> <p><code>ansible.cfg</code> method:</p> <p>ansible.cfg</p> <pre data-language="ini">[paramiko_connection]
host_key_auto_add = True
</pre>   <h3 id="error-no-authentication-methods-available">Error: “No authentication methods available”</h3> <p>For example:</p> <pre data-language="yaml">2017-04-04 12:19:05,670 p=18591 u=fred |  creating new control socket for host veos01:None as user admin
2017-04-04 12:19:05,670 p=18591 u=fred |  control socket path is /home/fred/.ansible/pc/ca5960d27a
2017-04-04 12:19:05,670 p=18591 u=fred |  current working directory is /home/fred/git/ansible-inc/ansible-workspace-2/test/integration
2017-04-04 12:19:05,670 p=18591 u=fred |  using connection plugin network_cli
2017-04-04 12:19:06,606 p=18591 u=fred |  connecting to host veos01 returned an error
2017-04-04 12:19:06,606 p=18591 u=fred |  No authentication methods available
2017-04-04 12:19:35,708 p=18591 u=fred |  connect retry timeout expired, unable to connect to control socket
2017-04-04 12:19:35,709 p=18591 u=fred |  persistent_connect_retry_timeout is 15 secs
</pre> <p>Suggestions to resolve:</p> <p>No password or SSH key supplied</p>   <h3 id="clearing-out-persistent-connections">Clearing Out Persistent Connections</h3> <p><strong>Platforms:</strong> Any</p> <p>In Ansible 2.3, persistent connection sockets are stored in <code>~/.ansible/pc</code> for all network devices. When an Ansible playbook runs, the persistent socket connection is displayed when verbose output is specified.</p> <p><code>&lt;switch&gt; socket_path: /home/fred/.ansible/pc/f64ddfa760</code></p> <p>To clear out a persistent connection before it times out (the default timeout is 30 seconds of inactivity), simple delete the socket file.</p>    <h2 id="timeout-issues">Timeout issues</h2>  <h3 id="timeouts">Timeouts</h3> <p>Persistent connection idle timeout:</p> <p>For example:</p> <pre data-language="yaml">2017-04-04 12:19:05,670 p=18591 u=fred |  persistent connection idle timeout triggered, timeout value is 30 secs
</pre> <p>Suggestions to resolve:</p> <p>Increase value of presistent connection idle timeout. .. code-block:: yaml</p>  export ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=60 <p>To make this a permanent change, add the following to your <code>ansible.cfg</code> file:</p> <pre data-language="ini">[persistent_connection]
connect_timeout = 60
</pre> <p>Command timeout: For example:</p> <pre data-language="yaml">2017-04-04 12:19:05,670 p=18591 u=fred |  command timeout triggered, timeout value is 10 secs
</pre> <p>Suggestions to resolve:</p> <p>Options 1: Increase value of command timeout in configuration file or by setting environment variable. Note: This value should be less than persistent connection idle timeout ie. connect_timeout</p> <pre data-language="yaml">export ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=30
</pre> <p>To make this a permanent change, add the following to your <code>ansible.cfg</code> file:</p> <pre data-language="ini">[persistent_connection]
command_timeout = 30
</pre> <p>Option 2: Increase command timeout per task basis. All network modules support a timeout value that can be set on a per task basis. The timeout value controls the amount of time in seconds before the task will fail if the command has not returned.</p> <p>For example:</p> <p>Suggestions to resolve:</p> <pre data-language="yaml">- name: save running-config
  ios_command:
    commands: copy running-config startup-config
    provider: "{{ cli }}"
    timeout: 30
</pre> <p>Some operations take longer than the default 10 seconds to complete. One good example is saving the current running config on IOS devices to startup config. In this case, changing the timeout value form the default 10 seconds to 30 seconds will prevent the task from failing before the command completes successfully. Note: This value should be less than persistent connection idle timeout ie. connect_timeout</p> <p>Persistent socket connect timeout: For example:</p> <pre data-language="yaml">2017-04-04 12:19:35,708 p=18591 u=fred |  connect retry timeout expired, unable to connect to control socket
2017-04-04 12:19:35,709 p=18591 u=fred |  persistent_connect_retry_timeout is 15 secs
</pre> <p>Suggestions to resolve:</p> <p>Increase value of presistent connection idle timeout. Note: This value should be greater than SSH timeout ie. timeout value under defaults section in configuration file and less than the value of the persistent connection idle timeout (connect_timeout)</p> <pre data-language="yaml">export ANSIBLE_PERSISTENT_CONNECT_RETRY_TIMEOUT=30
</pre> <p>To make this a permanent change, add the following to your <code>ansible.cfg</code> file:</p> <pre data-language="ini">[persistent_connection]
connect_retry_timeout = 30
</pre>    <h2 id="playbook-issues">Playbook issues</h2> <p>This section details issues are caused by issues with the Playbook itself.</p>  <h3 id="error-invalid-connection-specified-expected-connection-local-got-ssh">Error: “invalid connection specified, expected connection=local, got ssh”</h3> <p><strong>Platforms:</strong> Any</p> <p>Network modules require that the connection is set to <code>local</code>. Any other connection setting will cause the playbook to fail. Ansible will now detect this condition and return an error message:</p> <pre data-language="yaml">fatal: [nxos01]: FAILED! =&gt; {
    "changed": false,
    "failed": true,
    "msg": "invalid connection specified, expected connection=local, got ssh"
}
</pre> <p>To fix this issue, set the connection value to <code>local</code> using one of the following methods:</p> <ul class="simple"> <li>Set the play to use <code>connection: local</code>
</li> <li>Set the task to use <code>connection: local</code>
</li> <li>Run ansible-playbook using the <code>-c local</code> setting</li> </ul>   <h3 id="error-unable-to-enter-configuration-mode">Error: “Unable to enter configuration mode”</h3> <p><strong>Platforms:</strong> eos and ios</p> <p>This occurs when you attempt to run a task that requires privileged mode in a user mode shell.</p> <p>For example:</p> <pre data-language="yaml">TASK [ios_system : configure name_servers] *****************************************************************************
task path:
fatal: [ios-csr1000v]: FAILED! =&gt; {
    "changed": false,
    "failed": true,
   "msg": "unable to enter configuration mode",
}
</pre> <p>Suggestions to resolve:</p> <p>Add <code>authorize: yes</code> to the task. For example:</p> <pre data-language="yaml">- name: configure hostname
  ios_system:
    provider:
      hostname: foo
      authorize: yes
  register: result
</pre> <p>If the user requires a password to go into privileged mode, this can be specified with <code>auth_pass</code>; if <code>auth_pass</code> isn’t set, the environment variable <code id="index-3">ANSIBLE_NET_AUTHORIZE</code> will be used instead.</p> <p>Add <code>authorize: yes</code> to the task. For example:</p> <pre data-language="yaml">- name: configure hostname
  ios_system:
  provider:
    hostname: foo
    authorize: yes
    auth_pass: "{{ mypasswordvar }}"
register: result
</pre>
<div class="_attribution">
  <p class="_attribution-p">
    © 2012–2017 Michael DeHaan<br>© 2017 Red Hat, Inc.<br>Licensed under the GNU General Public License version 3.<br>
    <a href="https://docs.ansible.com/ansible/latest/network_debug_troubleshooting.html" class="_attribution-link" target="_blank">https://docs.ansible.com/ansible/latest/network_debug_troubleshooting.html</a>
  </p>
</div>

			</div>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
