
<!DOCTYPE HTML>

<html lang="en">

<head>
  <meta charset="utf-8">
  <title>numpy.geterrcall() - NumPy 1.13 - W3cubDocs</title>
  
  <meta name="description" content=" Return the current callback function used on floating-point errors. ">
  <meta name="keywords" content="numpy, geterrcall, -, numpy~1.13">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/numpy~1.13/generated/numpy.geterrcall/">
  <link href="/favicon.png" rel="icon">
  <link type="text/css" rel="stylesheet" href="/assets/application-e0f881b0fce8cbe96f33dadc355b7159d5d2912911231446d60eb8f9caffa802.css">
  <script type="text/javascript" src="/assets/application-8fc46316434047265cd383f02b8e7f434ed7dec4a59f920dd633deef8d488d1b.js"></script>
  <script src="/json/numpy~1.13.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/numpy~1.13/" class="_nav-link" title="" style="margin-left:0;">NumPy 1.13</a></span>
  
  <nav class="_nav">
    <a href="/app/" class="_nav-link ">App</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<div class="_page _sphinx">
				
<h1 id="numpy-geterrcall">numpy.geterrcall</h1> <dl class="function"> <dt id="numpy.geterrcall">
<code>numpy.geterrcall()</code> <a class="reference external" href="http://github.com/numpy/numpy/blob/v1.13.0/numpy/core/numeric.py#L2947-L2989" target="_blank"><span class="viewcode-link">[source]</span></a>
</dt> <dd>
<p>Return the current callback function used on floating-point errors.</p> <p>When the error handling for a floating-point error (one of “divide”, “over”, “under”, or “invalid”) is set to ‘call’ or ‘log’, the function that is called or the log instance that is written to is returned by <a class="reference internal" href="#numpy.geterrcall" title="numpy.geterrcall"><code>geterrcall</code></a>. This function or log instance has been set with <a class="reference internal" href="../numpy.seterrcall/#numpy.seterrcall" title="numpy.seterrcall"><code>seterrcall</code></a>.</p> <table class="docutils field-list" frame="void" rules="none"> <col class="field-name"> <col class="field-body">  <tr class="field-odd field">
<th class="field-name">Returns:</th>
<td class="field-body">
<p class="first"><strong>errobj</strong> : callable, log instance or None</p>  <p>The current error handler. If no handler was set through <a class="reference internal" href="../numpy.seterrcall/#numpy.seterrcall" title="numpy.seterrcall"><code>seterrcall</code></a>, <code>None</code> is returned.</p>  </td> </tr>  </table> <div class="admonition seealso"> <p class="first admonition-title">See also</p> <p class="last"><a class="reference internal" href="../numpy.seterrcall/#numpy.seterrcall" title="numpy.seterrcall"><code>seterrcall</code></a>, <a class="reference internal" href="../numpy.seterr/#numpy.seterr" title="numpy.seterr"><code>seterr</code></a>, <a class="reference internal" href="../numpy.geterr/#numpy.geterr" title="numpy.geterr"><code>geterr</code></a></p> </div> <h4 class="rubric">Notes</h4> <p>For complete documentation of the types of floating-point exceptions and treatment options, see <a class="reference internal" href="../numpy.seterr/#numpy.seterr" title="numpy.seterr"><code>seterr</code></a>.</p> <h4 class="rubric">Examples</h4> <pre data-language="python">&gt;&gt;&gt; np.geterrcall()  # we did not yet set a handler, returns None
</pre> <pre data-language="python">&gt;&gt;&gt; oldsettings = np.seterr(all='call')
&gt;&gt;&gt; def err_handler(type, flag):
...     print("Floating point error (%s), with flag %s" % (type, flag))
&gt;&gt;&gt; oldhandler = np.seterrcall(err_handler)
&gt;&gt;&gt; np.array([1, 2, 3]) / 0.0
Floating point error (divide by zero), with flag 1
array([ Inf,  Inf,  Inf])
</pre> <pre data-language="python">&gt;&gt;&gt; cur_handler = np.geterrcall()
&gt;&gt;&gt; cur_handler is err_handler
True
</pre> </dd>
</dl>
<div class="_attribution">
  <p class="_attribution-p">
    © 2008–2017 NumPy Developers<br>Licensed under the NumPy License.<br>
    <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.geterrcall.html" class="_attribution-link" target="_blank">https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.geterrcall.html</a>
  </p>
</div>

			</div>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
